# Linter Options
options:
  merge-default-rules: false
  formatter: stylish
  max-warnings: 50

# File Options
files:
  include: 'src/scss/**/*.s+(a|c)ss'

# Rule Configuration
rules:
  attribute-quotes:
    - 2
    - include: true
  border-zero:
    - 2
    - convention: none
  brace-style:
    - 2
    - allow-single-line: false
      style: 1tbs
  class-name-format:
    - 1
    - allow-leading-underscore: false
      convention: camelcase
  clean-import-paths: 1
  declarations-before-nesting: 1
  empty-args:
    - 2
    - include: true
  empty-line-between-blocks:
    - 2
    - include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 1
  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length: 1
  hex-notation:
    - 2
    - style: lowercase
  id-name-format:
    - 2
    - allow-leading-underscore: false
      convention: camelcase
  leading-zero:
    - 2
    - include: true
  max-file-line-count: 1
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations: 0
  nesting-depth: 0
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 1
  no-debug: 2
  no-disallowed-properties: 0
  no-duplicate-properties: 0
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-universal-selectors: 2
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 0
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  property-sort-order:
    - 1
    - order: recess
      ignore-custom-properties: true
  property-units: 0
  pseudo-element: 0
  quotes:
    - 2
    - style: single
  shorthand-values: 0
  single-line-per-selector: 2
  space-after-bang:
    - 2
    - include: false
  space-after-colon: 2
  space-after-comma: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon:
    - 2
    - include: false
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit:
    - 2
    - include: false
